### ISSUE TITLE
Audit request

### ISSUE THREAD

**Issue by spyder403** [akash-network/support#122]
Requesting audit for my nodes 
Jrgbuilding.org
Jrgbuilding.online

**Comment by andy108369** [comment]
- :warning: there is no `Jrgbuilding.online` provider based on the blockchain data;

Found only these two:

```
"https://provider.jrgbuilding.net:8443","akash190h2dkfeue3us46kt6yak5a0v48mxkvs9azw30"
"https://provider.jrgbuilding.org:8443","akash1js2a3tt8r7tuwavnpv04wdurthyx4vjwdppeld"
```

- :warning: `provider.jrgbuilding.net` - isn't responding over 8443/tcp
- `provider.jrgbuilding.org` - is responding over 8443/tcp


- :warning: `provider.jrgbuilding.org` provider is missing the `host: akash` attribute which is a necessary attribute for the community provider as per https://docs.akash.network/providers/akash-audited-attributes#attribute-auditors

```
$ provider-services query provider get akash1js2a3tt8r7tuwavnpv04wdurthyx4vjwdppeld -o text
attributes:
- key: organization
  value: Spyder
- key: capabilities/gpu/vendor/nvidia/model/4090
  value: "true"
- key: arch
  value: amd64
host_uri: https://provider.jrgbuilding.org:8443
info:
  email: ""
  website: ""
owner: akash1js2a3tt8r7tuwavnpv04wdurthyx4vjwdppeld
```

# checking `provider.jrgbuilding.org` provider
- [x] getting the bid (dseq 12873203)
- [x] nodePort is working
- [x] ingress address is working (*only when manually forwarding)
- [ ] ingress address is resolving
- [x] egress network (DNS/data) OK  (up/down speed 100/100)

```
$ provider_info.sh provider.jrgbuilding.org
type       cpu   gpu  ram                 ephemeral          persistent
used       6.2   13   8.15625             34.01171875        0
pending    0     0    0                   0                  0
available  25.3  0    243.02471542358398  855.9364657104015  0
node       25.3  0    243.02471542358398  855.9364657104015  N/A
```

## Issues

Ingress address name resolution is not working. Missing a wildcard DNS record for the `*.ingress.<provider>` address:

```
$ ping uugvvsaic9e2v8bd8qm3ci5vc4.ingress.jrgbuilding.org
ping: uugvvsaic9e2v8bd8qm3ci5vc4.ingress.jrgbuilding.org: Name or service not known
```

*Otherwise the ingress forwarding is working:

```
$ curl --connect-to uugvvsaic9e2v8bd8qm3ci5vc4.ingress.jrgbuilding.org:80:ingress.jrgbuilding.org:80 uugvvsaic9e2v8bd8qm3ci5vc4.ingress.jrgbuilding.org
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
...
```

**Comment by andy108369** [comment]
> I'm sorry hiw do I add wildcard dns

That's just `*` record that you need to add.

It looks like you are using namecheap.com

https://www.namecheap.com/support/knowledgebase/article.aspx/597/2237/how-can-i-set-up-a-catchall-wildcard-subdomain/
![image](https://github.com/akash-network/support/assets/107317698/39a5910c-c851-412a-8633-11b5e0b7c325)

You need to point the wildcard record `*.ingress` to the IP via DNS `A` record, or to the hostname via DNS `CNAME` record of your worker node address (IP or host)
Additionally - here is an example from the official Akash doc => https://docs.akash.network/providers/build-a-cloud-provider/akash-cloud-provider-build-with-helm-charts/step-5-domain-name-review

**Comment by andy108369** [comment]
@spyder403 any updates / help needed?

**Comment by andy108369** [comment]
both providers are down, owner hasn't responded.
Closing.
